# Server Port (permite que o Render defina a porta via variável de ambiente PORT)
server.port=${PORT:8080}

# Actuator
management.endpoints.web.exposure.include=health,info

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
